services:
  backend:
    build: .
    container_name: cinema_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:cywwig@db-cinema:5432/cinema?schema=dev-cinema"
      JWT_SECRET: "chave_secreta_super_segura_123"
    networks:
      - cinema-network

networks:
  cinema-network:
    external: true